### ISSUE TITLE
Event  Emitter Support

### ISSUE THREAD

**Issue by gorkemyontem** [needle-innovision/nestjs-tenancy#40]
Hi there, 
Is there any way this library works with event driven approach? https://docs.nestjs.com/techniques/events 

In the documentation they specifically state that "Event subscribers cannot be request-scoped." and your library is request-scoped. But I just want to make sure that there is a way or not. 

Thank you!

**Comment by sandeepsuvit** [comment]
@gorkemyontem Thanks for writing in.

Currently it is not supported since we derive the tenant information from the request data. But there is a PR for microservices with few modification of the core library methods which i haven't personally tested. You may find some pointers in that. https://github.com/needle-innovision/nestjs-tenancy/pull/38

**Comment by gorkemyontem** [comment]
Thank you @sandeepsuvit I'll follow that issue
